import { App, Component } from "vue";
export declare const registerComponent: (instance: App, component: Component) => void;
export declare const registerComponentProgrammatic: (instance: App, property: string, component: Component) => void;
export declare const typedEvent: <T extends Event>(event: Event) => T;
export declare const getEventTarget: <T extends HTMLElement>(event: Event) => T;
export declare type HTMLEvent<T extends HTMLElement> = Event & {
    source: T;
    target: T;
    bubbles: boolean;
    cancelBubble: boolean;
    cancelable: boolean;
    composed: boolean;
    currentTarget?: HTMLElement;
    defaultPrevented: boolean;
    eventPhase: number;
    isTrusted: boolean;
    path: HTMLElement[];
    returnValue: boolean;
    srcElement: T;
    timeStamp: 87349.17000000132;
    type: string;
};
